services:
- type: pserv
  name: mysql_zeus
  plan: standard
  env: docker
  autoDeploy: true
  disk:
    name: mysqldata
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
